### ISSUE TITLE
Leaf Position is incorrect

### ISSUE THREAD

**Issue by danwipf** [radiatoryang/hedera#5]
Incorrect results when using the Tool. (see the Leafs) any quick Idea how to fix this issue?
_(it's the ExampleIvyMeshExport.obj file inside the Example folder)_

![Hedera Leaf position](https://user-images.githubusercontent.com/42022126/64263845-a8453b00-cf30-11e9-94ee-d591e94e4924.PNG)

**Comment by radiatoryang** [comment]
I would probably want to look into this deeper / make leaf placement more user-configurable, but unfortunately I won't have time to work on this for a while...

some workarounds to try:
- rotate the leaf textures in Photoshop by 180 degrees, etc
- change the vertex order in IvyMesh.cs
- mess with the UV assignment in IvyMesh.cs

**Comment by danwipf** [comment]
i did tried to change the textures(rotation), manually add offset to the leafs didnt messed with the uv, because i believe they do not catch a point on the root/branch.

just to clarify i know how to manipulate a spline and can calculate a point on it but i didn’t figure out yet how it works here.

**Comment by radiatoryang** [comment]
https://github.com/radiatoryang/hedera/blob/b77406ca57132b6295c498b3a9a963917c33c1aa/Editor/Scripts/IvyMesh.cs#L424

it picks a point on the branch, adds random offset, and then uses that point as the center of the leaf quad...

a more accurate method maybe wouldn't add any random offset to the center -- and instead it would generate the leaf quad based on a random rotation around a pivot point, instead of the center of the leaf quad

(feel free to submit a PR if you get it working! or I'll get around to this in ~december)

**Comment by danwipf** [comment]
yes i will.

right now i can say that newLeafPos - ivygraphs current root position is an actual and correct point, so somewhere inside the center’s calculation the position gets off.

next respon i’ll add the solution as PR

dan

**Comment by radiatoryang** [comment]
finally got around to this a year later! see PR #8
