### ISSUE TITLE
Painting not working in Unity 2020.1.0a17

### ISSUE THREAD

**Issue by id-0-ru** [radiatoryang/hedera#6]
When I push "paint", click and drag mouse in editor window - nothing happened. I just select objects in editor, like usual. I'm using Unity 2020.1.0a17 and HDRP 7.1.7.

**Comment by radiatoryang** [comment]
sorry, didn't see this while on holiday --

I'm reluctant to try to fix this for an unreleased alpha version + preview HDRP since so much can change and so much might just be caused from general unity editor instability... maybe when they release 2020.1 for real, and HDRP leaves preview, then it'll make sense for me to look into it?

sorry for any inconvenience, but this is basically a "wait and see" thing to me

**Comment by Roland09** [comment]
I had the same in 2019.3.3f1. Problem was that Gizmos were disabled and hence OnSceneGUI never got invoked.

**Comment by Thats-Tyler** [comment]
> 
> 
> I had the same in 2019.3.3f1. Problem was that Gizmos were disabled and hence OnSceneGUI never got invoked.


Thank you for posting this!

**Comment by radiatoryang** [comment]
thanks for figuring this out, I added a warning for Unity 2019+ if it sees that gizmos are disabled

**Comment by BioSparkStudios** [comment]
I just reverted my windows back to default and it came back up.

**Comment by BioSparkStudios** [comment]
awesome project thanks for sharing
